site_name: Raw Rebalance Docs
nav:
  - Home: index.md
  - CIS:
    - Hero:
      - Asaj Ventress: cis/hero/asaj-ventress.md
      - Aurra Sing: cis/hero/aurra-sing.md
      - Bossk: cis/hero/bossk.md
      - Cat Bane: cis/hero/cat-bane.md
      - Count Docu: cis/hero/count-docu.md
      - Grievous: cis/hero/grievous.md
      - Jango: cis/hero/jango.md
      - Trench: cis/hero/trench.md
    - Land:
      - IG86: cis/land/ig86.md
      - Magmaguard: cis/land/magmaguard.md
      - Repair Droid: cis/land/repair-droid.md
    - Space:
      - Bomber: cis/space/bomber.md
      - Bulwark: cis/space/bulwark.md
      - Carrier: cis/space/carrier.md
      - Hammer Picket: cis/space/hammer-picket.md
      - Hyena: cis/space/hyena.md
      - Lucrehalk: cis/space/lucrehalk.md
      - Malevolence: cis/space/malevolence.md
      - Munificent: cis/space/munificent.md
      - Providence: cis/space/providence.md
      - Recusant: cis/space/recusant.md
      - Supply Ship: cis/space/supply-ship.md
      - Technounion Frigate: cis/space/technounion-frigate.md
      - Tri-Droid: cis/space/tri-droid.md
      - Vulture-Droid: cis/space/vulture-droid.md
      - Wavecrest: cis/space/wavecrest.md
  - Republic:
    - Hero:
      - Aayla Secura: rep/hero/aayla-secura.md
      - Anakin Skywalker: rep/hero/anakin-skywalker.md
      - Commander Cody: rep/hero/commander-cody.md
      - Deltasquad: rep/hero/deltasquad.md
      - Kit Fisto: rep/hero/kit-fisto.md
      - Luminara: rep/hero/luminara.md
      - Mace Windu: rep/hero/mace-windu.md
      - Obiwan: rep/hero/obiwan.md
      - Yoda: rep/hero/yoda.md
      - Yularen: rep/hero/yularen.md
    - Space:
      - Acclamator: rep/space/acclamator.md
      - Arc-170: rep/space/arc-170.md
      - Carrack: rep/space/carrack.md
      - Centax: rep/space/centax.md
      - CR-90: rep/space/cr-90.md
      - Dreadnaught: rep/space/dreadnaught.md
      - Freefall: rep/space/freefall.md
      - G-400: rep/space/g-400.md
      - Guardian Mantis: rep/space/guardian-mantis.md
      - Light Assault Cruiser: rep/space/light-assault-cruiser.md
      - Light Cruiser: rep/space/light-cruiser.md
      - Light Frigate: rep/space/light-frigate.md
      - Mandator: rep/space/mandator.md
      - NTB-630: rep/space/ntb-630.md
      - Pelta: rep/space/pelta.md
      - V19: rep/space/v19.md
      - Venator: rep/space/venator.md
      - Victory: rep/space/victory.md
  - About: about.md
theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 3
  collapse_navigation: true
  titles_only: true