# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow,
        # this defaults to the reference or SHA for that event. Otherwise, uses the default branch.
        ref: release # optional

    - name: steam-workshop-upload
      uses: weilbyte/steam-workshop-upload@v1
      with: 
        appid: 32470 # Game's Steam App ID
        itemid: 3131109252 # Your mod's Steam Workshop ID
        path: 'dist' # Path to your mod's folder from repository root
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
        STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)
